"""Resolve CI pins, then obtain release hashes from PyPI's HTTPS API.

Fetching all foreign-platform wheels just to hash them is unnecessary. The
official release JSON supplies their digests; pip --require-hashes still verifies
the actual selected wheel when installing on each CI platform.
"""

from __future__ import annotations

import argparse
from concurrent.futures import ThreadPoolExecutor
import json
from pathlib import Path
import re
import subprocess
import sys
from urllib.request import urlopen

from packaging.requirements import Requirement
from packaging.utils import canonicalize_name
from packaging.version import Version


def release_hashes(requirement: Requirement) -> tuple[str, tuple[str, ...]]:
    specs = list(requirement.specifier)
    if len(specs) != 1 or specs[0].operator != "==" or requirement.url:
        raise ValueError(f"CI dependency is not exactly pinned: {requirement}")
    name, version = canonicalize_name(requirement.name), specs[0].version
    with urlopen(
        f"https://pypi.org/pypi/{name}/{version}/json", timeout=30
    ) as response:
        data = json.load(response)
    if canonicalize_name(data["info"]["name"]) != name or Version(
        data["info"]["version"]
    ) != Version(version):
        raise ValueError("PyPI response does not match the requested release")
    hashes = sorted(
        {
            item["digests"]["sha256"]
            for item in data["urls"]
            if item["packagetype"] in {"bdist_wheel", "sdist"}
            and not item.get("yanked", False)
        }
    )
    if not hashes or any(
        re.fullmatch(r"[a-f0-9]{64}", digest) is None for digest in hashes
    ):
        raise ValueError(f"No valid non-yanked release hashes for {name}=={version}")
    return str(requirement), tuple(hashes)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--resolved",
        type=Path,
        help="Existing pip-compile output; otherwise resolve first",
    )
    options = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    resolved = options.resolved or root / "build" / "ci-pins.txt"
    if options.resolved is None:
        resolved.parent.mkdir(exist_ok=True)
        subprocess.run(
            [
                sys.executable,
                "-m",
                "piptools",
                "compile",
                "--allow-unsafe",
                "--strip-extras",
                "--output-file",
                str(resolved),
                str(root / "requirements" / "ci.in"),
            ],
            check=True,
            cwd=root,
            timeout=600,
        )
    requirements = []
    for raw in resolved.read_text(encoding="utf-8-sig").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("--"):
            raise ValueError(
                "CI pins must use official PyPI without embedded index overrides"
            )
        requirements.append(Requirement(line))
    if len({canonicalize_name(item.name) for item in requirements}) != len(
        requirements
    ):
        raise ValueError("duplicate resolved dependency")
    with ThreadPoolExecutor(max_workers=8) as pool:
        rows = list(pool.map(release_hashes, requirements))
    lines = [
        "# Generated by scripts/update_ci_lock.py.",
        "# Pins: pip-compile requirements/ci.in; SHA-256: official PyPI release JSON.",
        "# Install with pip --require-hashes. No local wheel paths or index overrides.",
        "",
    ]
    for requirement, hashes in sorted(rows):
        lines.append(requirement + " \\")
        for index, digest in enumerate(hashes):
            lines.append(
                "    --hash=sha256:"
                + digest
                + (" \\" if index + 1 < len(hashes) else "")
            )
    target = root / "requirements" / "ci.lock"
    temporary = target.with_suffix(".lock.tmp")
    temporary.write_text("\n".join(lines) + "\n", encoding="utf-8")
    temporary.replace(target)
    print(f"Locked {len(rows)} releases with verified PyPI SHA-256 metadata")


if __name__ == "__main__":
    main()
