"""Pi Agent Loop 的纯 Python 教学改写。"""

from .agent import Agent
from .cancellation import CancellationToken, OperationCancelledError
from .config import AgentLimits, load_agent_limits
from .event_stream import AgentEventStream, AssistantMessageEventStream, EventStream
from .loop import (
    agent_loop,
    agent_loop_continue,
    run_agent_loop,
    run_agent_loop_continue,
)
from .messages import assistant_message, empty_usage, now_ms, user_message
from .providers import (
    OpenAICompatibleProvider,
    ProviderConfigError,
    ProviderError,
    ProviderProfile,
    ProviderSettings,
    create_provider,
    load_provider_settings,
)
from .retry import (
    ModelRetryPolicy,
    OutcomeUnknownToolError,
    RetryableToolError,
    ToolRetryPolicy,
)
from .retry.circuit_breaker import (
    CircuitBreaker,
    CircuitBreakerPolicy,
    CircuitOpenError,
)
from .retry.compaction import (
    CompactionRetryPolicy,
    ContextOverflowCompactingStreamFn,
    SlidingWindowCompactor,
    compact_on_context_overflow,
)
from .retry.events import (
    JsonlRetryEventStore,
    RetryChain,
    RetryRecoveryManager,
)
from .retry.model import RetryingStreamFn, retry_model_stream
from .retry.outcome import OutcomeReconciliationRegistry
from .retry.task import (
    RetryableTaskError,
    TaskRetryExecutor,
    TaskRetryPolicy,
)
from .routing import (
    BusinessConfigError,
    CapabilityRegistry,
    HybridModelRouter,
    RequestDecision,
    RequiredToolCallGuard,
    RoutedAgent,
    RoutedPromptResult,
    SimpleBusinessConfig,
    SimpleDeniedRule,
    SimpleIntent,
    SimpleProduct,
    ToolCapability,
    ToolChoicePolicy,
    guard_stream_fn,
    load_simple_business_config,
)
from .testing import ScriptedProvider
from .tools import (
    ToolRegistry,
    create_add_tool,
    create_calculator_registry,
    create_calculator_tools,
    create_divide_tool,
    create_multiply_tool,
)
from .types import (
    AfterToolCallContext,
    AfterToolCallResult,
    AgentContext,
    AgentLoopConfig,
    AgentLoopTurnUpdate,
    AgentState,
    AgentTool,
    AgentToolResult,
    BeforeToolCallContext,
    BeforeToolCallResult,
    Model,
    TurnCompletedContext,
)

__all__ = [
    "Agent",
    "AgentContext",
    "AgentEventStream",
    "AgentLoopConfig",
    "AgentLimits",
    "AgentLoopTurnUpdate",
    "AgentState",
    "AgentTool",
    "AgentToolResult",
    "AfterToolCallContext",
    "AfterToolCallResult",
    "AssistantMessageEventStream",
    "BeforeToolCallContext",
    "BeforeToolCallResult",
    "BusinessConfigError",
    "CancellationToken",
    "CircuitBreaker",
    "CircuitBreakerPolicy",
    "CircuitOpenError",
    "CompactionRetryPolicy",
    "ContextOverflowCompactingStreamFn",
    "CapabilityRegistry",
    "EventStream",
    "HybridModelRouter",
    "JsonlRetryEventStore",
    "Model",
    "ModelRetryPolicy",
    "OperationCancelledError",
    "OpenAICompatibleProvider",
    "OutcomeReconciliationRegistry",
    "OutcomeUnknownToolError",
    "ProviderConfigError",
    "ProviderError",
    "ProviderProfile",
    "ProviderSettings",
    "RequestDecision",
    "RetryableTaskError",
    "RetryableToolError",
    "RetryingStreamFn",
    "RequiredToolCallGuard",
    "RoutedAgent",
    "RetryChain",
    "RetryRecoveryManager",
    "RoutedPromptResult",
    "ScriptedProvider",
    "SlidingWindowCompactor",
    "SimpleBusinessConfig",
    "SimpleDeniedRule",
    "SimpleIntent",
    "SimpleProduct",
    "TaskRetryExecutor",
    "TaskRetryPolicy",
    "ToolCapability",
    "ToolChoicePolicy",
    "ToolRetryPolicy",
    "ToolRegistry",
    "TurnCompletedContext",
    "agent_loop",
    "agent_loop_continue",
    "assistant_message",
    "create_add_tool",
    "create_calculator_registry",
    "create_calculator_tools",
    "create_divide_tool",
    "create_multiply_tool",
    "compact_on_context_overflow",
    "create_provider",
    "empty_usage",
    "guard_stream_fn",
    "load_agent_limits",
    "load_provider_settings",
    "load_simple_business_config",
    "now_ms",
    "run_agent_loop",
    "retry_model_stream",
    "run_agent_loop_continue",
    "user_message",
]
