"""Pi Agent Loop 的纯 Python 教学改写。"""

from .agent import Agent
from .approval import ApprovalError, ApprovalRecord, ApprovalService
from .cancellation import CancellationToken, OperationCancelledError
from .config import AgentLimits, load_agent_limits
from .domains import (
    DomainEvent,
    DomainStateMachine,
    DomainTransition,
    DomainTransitionError,
    EntityState,
)
from .event_stream import AgentEventStream, AssistantMessageEventStream, EventStream
from .harness import (
    ApprovalResumeCoordinator,
    DurableAgentHost,
    DurableHostPromptResult,
    PendingApprovalResume,
    RecoverableModelRuntime,
    RecoverableToolRuntime,
    StartupRecoveryCoordinator,
    StartupRecoveryReport,
)
from .loop import (
    agent_loop,
    agent_loop_continue,
    run_agent_loop,
    run_agent_loop_continue,
)
from .messages import assistant_message, empty_usage, now_ms, user_message
from .providers import (
    OpenAICompatibleProvider,
    ProviderConfigError,
    ProviderError,
    ProviderProfile,
    ProviderSettings,
    create_provider,
    load_provider_settings,
)
from .retry import (
    ModelRetryPolicy,
    OutcomeUnknownToolError,
    RetryableToolError,
    ToolRetryPolicy,
)
from .retry.circuit_breaker import (
    CircuitBreaker,
    CircuitBreakerPolicy,
    CircuitOpenError,
)
from .retry.compaction import (
    CompactionRetryPolicy,
    ContextOverflowCompactingStreamFn,
    SlidingWindowCompactor,
    compact_on_context_overflow,
)
from .retry.events import (
    JsonlRetryEventStore,
    RetryChain,
    RetryRecoveryManager,
)
from .retry.model import RetryingStreamFn, retry_model_stream
from .retry.outcome import OutcomeReconciliationRegistry
from .retry.task import (
    RetryableTaskError,
    TaskRetryExecutor,
    TaskRetryPolicy,
)
from .routing import (
    BusinessConfigError,
    CapabilityRegistry,
    HybridModelRouter,
    RequestDecision,
    RequiredToolCallGuard,
    RoutedAgent,
    RoutedPromptResult,
    SimpleBusinessConfig,
    SimpleDeniedRule,
    SimpleIntent,
    SimpleProduct,
    ToolCapability,
    ToolChoicePolicy,
    guard_stream_fn,
    load_simple_business_config,
)
from .runtime import (
    RunState,
    RuntimeEvent,
    RuntimeInvariantError,
    RuntimeStateTracker,
    ToolCallState,
    project_runtime_state,
    reduce_runtime_state,
)
from .security import (
    IdentityClaim,
    IdentityVerificationError,
    StaticIdentityVerifier,
    VerifiedIdentity,
)
from .session import (
    DurableOperationRecorder,
    DurableSessionRecovery,
    InMemoryOperationEventStore,
    InMemoryRuntimeEventStore,
    JsonlOperationEventStore,
    JsonlRuntimeEventStore,
    OperationRecoveryPlan,
    OperationState,
    RecoveryAction,
    RecoveryCallbacks,
    RecoveryExecutionResult,
    RuntimeRecoveryManager,
    replay_operation,
    replay_runtime_events,
)
from .testing import ScriptedProvider
from .transcript import (
    TranscriptIntegrityError,
    analyze_tool_call_transcript,
    repair_unresolved_tool_calls,
    validate_closed_tool_call_transcript,
)
from .tools import (
    ToolRegistry,
    create_add_tool,
    create_calculator_registry,
    create_calculator_tools,
    create_divide_tool,
    create_multiply_tool,
)
from .types import (
    AfterToolCallContext,
    AfterToolCallResult,
    AgentContext,
    AgentLoopConfig,
    AgentLoopTurnUpdate,
    AgentState,
    AgentTool,
    AgentToolResult,
    BeforeToolCallContext,
    BeforeToolCallResult,
    Model,
    TurnCompletedContext,
)
from .writes import WriteOperation, WriteOperationError, WriteOperationService

__all__ = [
    "Agent",
    "AgentContext",
    "AgentEventStream",
    "AgentLoopConfig",
    "AgentLimits",
    "AgentLoopTurnUpdate",
    "AgentState",
    "AgentTool",
    "AgentToolResult",
    "ApprovalError",
    "ApprovalRecord",
    "ApprovalResumeCoordinator",
    "ApprovalService",
    "AfterToolCallContext",
    "AfterToolCallResult",
    "AssistantMessageEventStream",
    "BeforeToolCallContext",
    "BeforeToolCallResult",
    "BusinessConfigError",
    "CancellationToken",
    "CircuitBreaker",
    "CircuitBreakerPolicy",
    "CircuitOpenError",
    "CompactionRetryPolicy",
    "ContextOverflowCompactingStreamFn",
    "CapabilityRegistry",
    "DomainEvent",
    "DomainStateMachine",
    "DomainTransition",
    "DomainTransitionError",
    "DurableAgentHost",
    "DurableHostPromptResult",
    "DurableOperationRecorder",
    "DurableSessionRecovery",
    "EntityState",
    "EventStream",
    "HybridModelRouter",
    "IdentityClaim",
    "IdentityVerificationError",
    "InMemoryOperationEventStore",
    "InMemoryRuntimeEventStore",
    "JsonlOperationEventStore",
    "JsonlRetryEventStore",
    "JsonlRuntimeEventStore",
    "Model",
    "ModelRetryPolicy",
    "OperationCancelledError",
    "OpenAICompatibleProvider",
    "PendingApprovalResume",
    "OutcomeReconciliationRegistry",
    "OperationRecoveryPlan",
    "OperationState",
    "OutcomeUnknownToolError",
    "ProviderConfigError",
    "ProviderError",
    "ProviderProfile",
    "ProviderSettings",
    "RecoveryAction",
    "RecoveryCallbacks",
    "RecoveryExecutionResult",
    "RecoverableModelRuntime",
    "RecoverableToolRuntime",
    "RequestDecision",
    "RetryableTaskError",
    "RetryableToolError",
    "RetryingStreamFn",
    "RequiredToolCallGuard",
    "RunState",
    "RuntimeEvent",
    "RuntimeInvariantError",
    "RuntimeRecoveryManager",
    "RuntimeStateTracker",
    "RoutedAgent",
    "RetryChain",
    "RetryRecoveryManager",
    "RoutedPromptResult",
    "ScriptedProvider",
    "SlidingWindowCompactor",
    "SimpleBusinessConfig",
    "SimpleDeniedRule",
    "SimpleIntent",
    "SimpleProduct",
    "StartupRecoveryCoordinator",
    "StartupRecoveryReport",
    "StaticIdentityVerifier",
    "TaskRetryExecutor",
    "TaskRetryPolicy",
    "ToolCallState",
    "TranscriptIntegrityError",
    "ToolCapability",
    "ToolChoicePolicy",
    "ToolRetryPolicy",
    "ToolRegistry",
    "TurnCompletedContext",
    "VerifiedIdentity",
    "WriteOperation",
    "WriteOperationError",
    "WriteOperationService",
    "agent_loop",
    "agent_loop_continue",
    "analyze_tool_call_transcript",
    "assistant_message",
    "create_add_tool",
    "create_calculator_registry",
    "create_calculator_tools",
    "create_divide_tool",
    "create_multiply_tool",
    "compact_on_context_overflow",
    "create_provider",
    "empty_usage",
    "guard_stream_fn",
    "load_agent_limits",
    "load_provider_settings",
    "load_simple_business_config",
    "now_ms",
    "project_runtime_state",
    "reduce_runtime_state",
    "repair_unresolved_tool_calls",
    "replay_operation",
    "replay_runtime_events",
    "run_agent_loop",
    "retry_model_stream",
    "run_agent_loop_continue",
    "user_message",
    "validate_closed_tool_call_transcript",
]
